### ISSUE TITLE
#6 A home page

### ISSUE THREAD

**Issue by yuxiang-zhang** [LouisBenjamin/UC3-Team-Project#19]
User Story: 
As a user, I want to have an overview of what the website offers so I can access different features easily. 

#2 #6 #12 As part of sprint 2, the following tasks are required:  
- [x] Design menu bar #21 
- [x] Design home feed (how posts will be organized) #22

**Comment by harrisonahn** [comment]
Shouldn't the navigation bar be essential in order to search for people to follow?
