### ISSUE TITLE
#6  #12 Add a Profile and Settings button on a users home page.

### ISSUE THREAD

**Issue by HarishJayasankar** [LouisBenjamin/UC3-Team-Project#21]
#6 , #12

Add a Profile and Settings button at the corner of the home screen. So,  the user can use that to go to his profile and log out from his account.

**Comment by yuxiang-zhang** [comment]
I believe this is covered in issue #19 menu bar, it shouldn't be a Sub Story but rather a smaller task.

**Comment by HarishJayasankar** [comment]
Yeah, I know but this Profile and Settings button is very important, for some functionalities as I mentioned in the comment. So, I think it's better to keep it as substory.
