### ISSUE TITLE
#6 Add a new tweet widow/column on the home page and Profile page.

### ISSUE THREAD

**Issue by HarishJayasankar** [LouisBenjamin/UC3-Team-Project#22]
#6 
Tweet window should be created with tweet/post button. So, the user can post his message.

**Comment by yuxiang-zhang** [comment]
I mean, this is also covered in #19... You are paraphrasing everything I mentioned?

**Comment by HarishJayasankar** [comment]
I think that's better.the functionalities which we need to develop will be clear.

**Comment by yuxiang-zhang** [comment]
I think it is rather messy. There is no clear hierarchy between Sub Stories as the number of issues go up. I would prefer not to confuse Sub Stories with Tasks.

**Comment by LouisBenjamin** [comment]
@yuxiang-zhang is right, this is the same as creating the home page. Closed.
