### ISSUE TITLE
#23 #47 User session implementation

### ISSUE THREAD

**Issue by yuxiang-zhang** [LouisBenjamin/UC3-Team-Project#49]
Session is not well-implemented. Possibly requires factoring out session setup. 

- [x] Login Session
- [x] Ability to log out

**Comment by abirshah** [comment]
you rewrite the code , however i did the implementation.

**Comment by yuxiang-zhang** [comment]
> 
> 
> you rewrite the code , however i did the implementation.

Credit is all yours. If that means something.

**Comment by LouisBenjamin** [comment]
- [ ] Login Session
- [ ] Ability to log out
