### ISSUE TITLE
Upload pictures

### ISSUE THREAD

**Issue by yuxiang-zhang** [LouisBenjamin/UC3-Team-Project#61]
User story: 
As a blog user, I want to upload pictures as my profile photo. 

Tasks: 
- [x] Add button to profile page

- [x] Link button to update database

- [x] Dynamically show/hide button

- [x] Unit test #65 

- [x] Acceptance test #67 

![capture](https://user-images.githubusercontent.com/24642918/54040380-2fd50b80-4193-11e9-92a3-78e3d6bfb01b.PNG)

**Comment by LouisBenjamin** [comment]
![image](https://user-images.githubusercontent.com/24642918/54008961-f078d180-4136-11e9-8645-422ff7ace867.png)

**Comment by yuxiang-zhang** [comment]
610271a9be0161c31d3de4d48dd4c2fb2cc2984c Did the unit test
