### ISSUE TITLE
Everybody  needs to create own one branch from master

### ISSUE THREAD

**Issue by abirshah** [LouisBenjamin/UC3-Team-Project#8]

**Comment by abirshah** [comment]
I have created my branch.

**Comment by yuxiang-zhang** [comment]
I think that a branch exists based on need. We haven't really started the project. There shouldn't be so many branches to confuse everything.

**Comment by abirshah** [comment]
all the team members have to create a branch. because every one needs to put their code in their own 
branch first from, they are going to merge to the master branch

**Comment by yuxiang-zhang** [comment]
> 
> 
> all the team members have to create a branch. because every one needs to put their code in their own
> branch first from, they are going to merge to the master branch

I'm not sure if everyone is coding in the project.
