### ISSUE TITLE
Create scrum and weekly meeting summary in Wiki

### ISSUE THREAD

**Issue by abirshah** [LouisBenjamin/UC3-Team-Project#9]

**Comment by yuxiang-zhang** [comment]
The email from the professor says the meeting summary can be recorded under the relevant issues.

**Comment by HarishJayasankar** [comment]
Yes,abirshah is right. We have to create meeting summary in Wiki.

**Comment by HarishJayasankar** [comment]
> > The email from the professor says the meeting summary can be recorded under the relevant issues.
> 
> i don't know, if you remember, i was asking TA about it in the last tutorial. he told me to use Wiki

Yes,you are right. We have to create meeting summary in Wiki.

**Comment by yuxiang-zhang** [comment]
Alright. I’m not concerned with where it will be created, as long as it’s done.

**Comment by abirshah** [comment]
Scrum and Weekly meeting added to Wiki
